name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/conda-forge
  - https://repo.mamba.pm/emscripten-forge
dependencies:
  - ipycanvas
  - matplotlib
  - ipympl
  - lmfit
  - regex
  - pyserial
