name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - numpy
  - ipycanvas
  - matplotlib
  - ipympl
  - lmfit
  - regex
  - pyserial
  - jupyterlab-spreadsheet-editor
