name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/conda-forge
  - https://repo.mamba.pm/emscripten-forge
dependencies:
  - ipycanvas
  - matplotlib
  - numpy=1.23.4
  - scipy
  - ipympl
  - lmfit
  - regex
